package projetSpringBoot.service;

import projetSpringBoot.model.Ingredients.AssociationIngredientRecette;
import projetSpringBoot.model.Ingredients.AssociationIngredientRecetteKey;

public interface AssociationIngredientRecetteService
		extends GenericInterfaceService<AssociationIngredientRecette, AssociationIngredientRecetteKey> {

}